// Mirrors the reference that Expo writes into `expo-env.d.ts`.
//
// `expo-env.d.ts` is generated by the Expo CLI and is git ignored, so CI only
// ever sees a checkout without it. That file is what pulls in `expo/types`,
// which declares `*.css` for side-effect imports like `import "@/global.css"`.
// TypeScript 6 (SDK 57) errors on side-effect imports with no declaration
// (TS2882), so the type check passed locally and failed in CI.
//
// Keeping the reference in a committed file makes `tsc` behave the same in
// both places. Safe alongside `expo-env.d.ts` — duplicate references dedupe.
/// <reference types="expo/types" />
